version: 2
updates:
- package-ecosystem: cargo
  directory: "/native"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: neon-build
    versions:
    - 0.5.3
    - 0.7.0
  - dependency-name: neon
    versions:
    - 0.6.0
    - 0.7.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: neon-cli
    versions:
    - 0.6.0
    - 0.7.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
