[package]
name = "node-eyeliner"
version = "0.0.0"
build = "build.rs"

[lib]
name = "node_eyeliner"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
eyeliner = { git = "https://github.com/dfrankland/eyeliner.git" }
